services:
  - name: ruyi
    type: web
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails server
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
