services:
  - name: ruyi
    type: web
    env: ruby
    buildCommand: "./bin/render-build.sh"
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ruyi-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
databases:
  - name: ruyi-db
    ipAllowList: []
